name: using_PAT_workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use PAT for authentication
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          echo "${{ secrets.PAT }}" | gh auth login --with-token
